hydra:
  job:
    chdir: True
  run:
    dir: ./output/ppo/${now:%Y-%m-%d_%H%M%S_%f}/

seed: 0

total_timesteps: 1e6
num_steps: 10
num_envs: 2048
update_epochs: 4
num_minibatches: 32
learning_rate: 3e-4
max_grad_norm: 0.5

gamma: 0.99
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.0
vf_coef: 0.5

activation: tanh

env_path: /workdir/omni_epic/envs/wall_is_lava.py
episode_length: 1000
action_repeat: 1
normalize_env: False

debug: True
